"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ExternalLink, Github, ChevronDown, ChevronUp } from "lucide-react";

const projects = [
  {
    id: 1,
    title: "Photo Gallery",
    description:
      "Created a photo gallery website to showcase artistic photos and works",
    image: "/placeholder.svg?height=300&width=500",
    technologies: [
      "Next.js",
      "TypeScript",
      "Shadcn/ui",
      "Framer Motion",
      "React Hook Form",
      "MongoDB",
      "Cloudinary",
      "CSS",
    ],
    role: "A modern, responsive portfolio built with Next.js 14 and TypeScript, featuring a dynamic gallery, secure admin dashboard, and interactive contact system. Designed with shadcn/ui, Framer Motion animations, it blends creativity with sleek, efficient technology.",
    liveLink: "#",
    githubLink: "#",
    expanded: false,
    liveDemo: false,
  },
  {
    id: 2,
    title: "Live Streaming Application",
    description:
      "Advanced web portal for seamless live streaming across YouTube, Facebook, and Vimeo platforms.",
    image: "/placeholder.svg?height=300&width=500",
    technologies: [
      "React.js",
      "CSS",
      "AWS Lambda",
      "API Gateway",
      "Stripe",
      "CloudFormation",
    ],
    role: "Created advanced web portal designed to facilitate seamless live streaming across major social media platforms. Implemented comprehensive integrations with APIs from YouTube, Facebook, Vimeo, and other platforms. Developed and deployed a robust subscription model using Stripe, offering a range of customizable plans to suit diverse user needs.",
    liveLink: "#",
    githubLink: "#",
    expanded: false,
    liveDemo: false,
  },
  {
    id: 3,
    title: "Real Estate E-commerce Platform",
    description:
      "Cutting-edge platform built on Next.js, offering seamless buying and selling of homes and properties.",
    image: "/placeholder.svg?height=300&width=500",
    technologies: ["Next.js", "React", "Material UI", "Node.js", "MongoDB"],
    role: "Built a platform where users can register as buyers or sellers, enabling tailored experiences based on their role. Sellers can list properties for sale, while buyers can explore detailed listings, schedule virtual tours, and purchase properties. The platform includes integrated e-contract signing capabilities for secure transactions. All property-related documentation is managed and generated by an authorized admin, ensuring compliance and authenticity.",
    liveLink: "#",
    githubLink: "#",
    expanded: false,
    liveDemo: false,
  },
  {
    id: 4,
    title: "Bakery E-commerce Admin Portal",
    description:
      "Robust B2C Admin portal for a bakery e-commerce platform with role-based access control.",
    image: "/placeholder.svg?height=300&width=500",
    technologies: [
      "Next.js",
      "TypeScript",
      "Ant Design",
      "Firebase",
      "Geolocation API",
    ],
    role: "Developed a robust B2C Admin portal for a bakery e-commerce platform, streamlining operations for Super Admin, Warehouse Admin, and Pickup Admin roles, and integrating advanced location-based services. Spearheaded the implementation of a secure, role-based authentication system, enabling controlled access for three distinct administrative roles while enhancing workflow efficiency across departments.",
    liveLink: "#",
    githubLink: "#",
    expanded: false,
    liveDemo: false,
  },
  {
    id: 5,
    title: "Funding Platform for Stakeholders",
    description:
      "Sophisticated platform facilitating seamless interactions between funders and fundees.",
    image: "/placeholder.svg?height=300&width=500",
    technologies: ["Next.js", "React", "Redux", "Material UI", "GraphQL"],
    role: "Led the development of a sophisticated platform facilitating seamless interactions between funders and fundees, handling complex form structures and workflows. The project involved deep API integration, creation of custom components tailored to user needs, and the seamless incorporation of dynamic themes, all within the Next.js framework.",
    liveLink: "#",
    githubLink: "#",
    expanded: false,
    liveDemo: false,
  },
  {
    id: 6,
    title: "Efficient Compliance Training Portal",
    description:
      "Mobile-friendly healthcare portal designed for medical professionals and small business owners.",
    image: "/placeholder.svg?height=300&width=500",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "PostgreSQL"],
    role: "Created a mobile-friendly healthcare portal designed for medical professionals and small business owners, providing personalized, interactive courses tailored to users' educational backgrounds and training needs, with comprehensive course and user data managed via an intuitive admin web portal.",
    liveLink: "#",
    githubLink: "#",
    expanded: false,
    liveDemo: false,
  },
];

export default function Projects() {
  const [expandedId, setExpandedId] = useState<number | null>(null);
  const [filter, setFilter] = useState<string | null>(null);

  const toggleExpand = (id: number) => {
    setExpandedId(expandedId === id ? null : id);
  };

  const filteredProjects = filter
    ? projects.filter((project) =>
        project.technologies.some((tech) =>
          tech.toLowerCase().includes(filter.toLowerCase())
        )
      )
    : projects;

  return (
    <section id="projects" className="py-20 bg-muted/30">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl md:text-4xl font-bold mb-4">My Projects</h2>
          <div className="w-20 h-1 bg-primary mx-auto mb-6"></div>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Here are some of the projects I&apos;ve worked on throughout my
            career.
          </p>
        </motion.div>

        {/* Creative filter chips */}
        <div className="relative mb-16 max-w-4xl mx-auto">
          <div className="flex flex-wrap justify-center gap-3 mb-6">
            <motion.button
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              className={`px-4 py-2 rounded-full transition-all ${
                filter === null
                  ? "bg-primary text-primary-foreground shadow-md"
                  : "bg-muted hover:bg-primary/10"
              }`}
              onClick={() => setFilter(null)}
            >
              All Projects
            </motion.button>

            {Array.from(
              new Set(projects.flatMap((project) => project.technologies))
            ).map((tech) => (
              <motion.button
                key={tech}
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className={`px-4 py-2 rounded-full transition-all ${
                  filter === tech
                    ? "bg-primary text-primary-foreground shadow-md"
                    : "bg-muted hover:bg-primary/10"
                }`}
                onClick={() => setFilter(tech)}
              >
                {tech}
              </motion.button>
            ))}
          </div>

          {filter && (
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="text-center text-sm text-muted-foreground"
            >
              Showing projects using{" "}
              <span className="font-semibold text-primary">{filter}</span>
              <button
                className="ml-2 text-primary hover:underline"
                onClick={() => setFilter(null)}
              >
                (Clear filter)
              </button>
            </motion.div>
          )}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <AnimatePresence>
            {filteredProjects.map((project, index) => (
              <motion.div
                key={project.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                layout
              >
                <Card className="h-full flex flex-col overflow-hidden border-none shadow-lg hover:shadow-xl transition-all duration-300">
                  <div className="overflow-hidden">
                    <img
                      src={project.image || "/placeholder.svg"}
                      alt={project.title}
                      className="w-full h-48 object-cover transition-transform duration-500 hover:scale-105"
                    />
                  </div>
                  <CardHeader className="bg-gradient-to-r from-primary/5 to-transparent">
                    <CardTitle>{project.title}</CardTitle>
                    <CardDescription>{project.description}</CardDescription>
                  </CardHeader>
                  <CardContent className="flex-grow">
                    <div className="flex flex-wrap gap-2 mb-4">
                      {project.technologies.slice(0, 3).map((tech) => (
                        <span
                          key={tech}
                          className="px-2 py-1 bg-primary/10 text-primary text-xs rounded-full"
                        >
                          {tech}
                        </span>
                      ))}
                      {project.technologies.length > 3 && (
                        <span className="px-2 py-1 bg-muted text-muted-foreground text-xs rounded-full">
                          +{project.technologies.length - 3} more
                        </span>
                      )}
                    </div>
                    <AnimatePresence>
                      {expandedId === project.id && (
                        <motion.div
                          initial={{ opacity: 0, height: 0 }}
                          animate={{ opacity: 1, height: "auto" }}
                          exit={{ opacity: 0, height: 0 }}
                          transition={{ duration: 0.3 }}
                        >
                          <h4 className="font-semibold mb-2">My Role:</h4>
                          <p className="text-muted-foreground mb-4">
                            {project.role}
                          </p>

                          <h4 className="font-semibold mb-2">Technologies:</h4>
                          <div className="flex flex-wrap gap-2 mb-4">
                            {project.technologies.map((tech) => (
                              <span
                                key={tech}
                                className="px-2 py-1 bg-primary/10 text-primary text-xs rounded-full"
                              >
                                {tech}
                              </span>
                            ))}
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="p-0 h-auto text-primary hover:text-primary/80 hover:bg-transparent"
                      onClick={() => toggleExpand(project.id)}
                    >
                      {expandedId === project.id ? (
                        <>
                          <ChevronUp className="mr-1 h-4 w-4" />
                          Show less
                        </>
                      ) : (
                        <>
                          <ChevronDown className="mr-1 h-4 w-4" />
                          Show more
                        </>
                      )}
                    </Button>
                  </CardContent>
                  <CardFooter className="flex justify-between bg-muted/30">
                    {project.liveDemo && (
                      <>
                        <Button
                          variant="outline"
                          size="sm"
                          className="rounded-full"
                          asChild
                        >
                          <a
                            href={project.liveLink}
                            target="_blank"
                            rel="noopener noreferrer"
                          >
                            <ExternalLink className="mr-2 h-4 w-4" />
                            Live Demo
                          </a>
                        </Button>
                        <Button
                          variant="outline"
                          size="sm"
                          className="rounded-full"
                          asChild
                        >
                          <a
                            href={project.githubLink}
                            target="_blank"
                            rel="noopener noreferrer"
                          >
                            <Github className="mr-2 h-4 w-4" />
                            Code
                          </a>
                        </Button>
                      </>
                    )}
                  </CardFooter>
                </Card>
              </motion.div>
            ))}
          </AnimatePresence>
        </div>
      </div>
    </section>
  );
}
